/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hal_NativeCall */

#ifndef _Included_com_example_hal_NativeCall
#define _Included_com_example_hal_NativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hal_NativeCall
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hal_NativeCall_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    CameraOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_CameraOn
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    CameraOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_CameraOff
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    MicrophoneOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_MicrophoneOn
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    MicrophoneOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_MicrophoneOff
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    SDCardOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_SDCardOn
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    SDCardOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_SDCardOff
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    GPSOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_GPSOn
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    GPSOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_GPSOff
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    MobileOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_MobileOn
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    MobileOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_MobileOff
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    WifiOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_WifiOn
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    WifiOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_WifiOff
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    BluetoothOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_BluetoothOn
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hal_NativeCall
 * Method:    BluetoothOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hal_NativeCall_BluetoothOff
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
